### ISSUE TITLE
Mixing recipes with tomato sauce don't return bowl

### ISSUE THREAD

**Issue by benyap** [PssbleTrngle/SliceAndDice#108]
### What happened?

I noticed that the mixing recipes added by SliceAndDice that involve tomato sauce (`farmersdelight:tomato_sauce`) don't return the wooden bowl. When you cook with the Farmer's Delight cooking pot, tomato sauce will generally eject a bowl after using tomato sauce.

Mixing recipes involving cooked rice (`farmersdelight:cooked_rice`) produce the extra bowl as expected.

### Loader

fabric

### Mod Version

3.0.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
In my opinion this is caused by create (fabric or forge) because the handle crafting remainders incorrect for basin recipes, I have opened an issue on both repos: [Fabric](https://github.com/Fabricators-of-Create/Create/issues/1607), [Forge](https://github.com/Creators-of-Create/Create/issues/6963).

In the next release of slice & dice for fabric I will finally release the feature which converts item ingredients, which can be emptied into a fluid to be swapped in the recipe with that fluid. This will not solve this bug, but at least at an alternative for some recipes (mostly those requiring milk buckets)

**Comment by PssbleTrngle** [comment]
Should be fixed now for at least forge

**Comment by temp-username261** [comment]
still happens in forge
minecraft 1.21.1 with mod version 4.3.3
making fish stew uses tomato sauce, and does not return the bowl
i assume this also applies to other recipes in the mod
