### ISSUE TITLE
Slicer visual glitch

### ISSUE THREAD

**Issue by the-most-bruh** [PssbleTrngle/SliceAndDice#205]
### What happened?

visual glitch with the Slicer not showing the slicing part and the cog inside 

![Image](https://github.com/user-attachments/assets/1c164334-cb03-4e5b-adfa-6294008f4cea)

### Loader

neoforge

### Mod Version

4.0.1

### Minecraft Version

1.21

### Relevant log output

```Shell

```

**Comment by the-most-bruh** [comment]
works fine though can confirm no crash

**Comment by Henka42** [comment]
I have the same issue, it seems to be caused by the presence of other mods, including [Functional Storage](https://www.curseforge.com/minecraft/mc-mods/functional-storage), [Observable](https://www.curseforge.com/minecraft/mc-mods/observable), [Just Blahaj](https://www.curseforge.com/minecraft/mc-mods/justblahaj), [Gliders](https://www.curseforge.com/minecraft/mc-mods/gliders), [Iron Chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests) and [Fast Leaf Decay](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay).

With Observable, the tool in the slicer is displayed.
With Functional Storage, Just Blahaj, Gliders, Iron Chests and Fast Leaf Decay, the tool in the slicer is invisible.

**Comment by the-most-bruh** [comment]
No none of those mods are included in the pack in the photo I might have something else but it’s not a problem

**Comment by Henka42** [comment]
It's not a complete list, each of these mods cause this issue in my modpack, in yours it may be other mod(s). I provided this list to help debugging.

**Comment by the-most-bruh** [comment]
Yes I’m to lazy to find mine and again it’s not bothering me that much so

**Comment by fabien-gigante** [comment]
Same problem here, with a different set of mods.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d9eddf34-7172-412c-8e47-e0e2db857096" />

<details><summary>Mod list</summary>
```

     Mod List:
		Name Version (Mod Id)

		Advancements Reloaded 0.6.1 (advancements_reloaded)
		Alternate Current 1.9.0 (alternate_current)
		AppleSkin 3.0.5+mc1.21 (appleskin)
		Architectury 13.0.8 (architectury)
		Armor Stand Poses 1.3.0 (poses)
		BetterF3 11.0.3 (betterf3)
		ClickThrough Plus 3.4+1.21.1 (clickthrough)
		Cloth Config v15 API 15.0.140 (cloth_config)
		Concurrent Chunk Management Engine 0.3.0+alpha.0.71+1.21.1 (c2me)
		Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.71+1.21.1 (c2me_base)
		Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.0+alpha.0.71+1.21.1 (c2me_client_uncapvd)
		Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.71+1.21.1 (c2me_fixes_chunkio_threading_issues)
		Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.71+1.21.1 (c2me_fixes_general_threading_issues)
		Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.71+1.21.1 (c2me_fixes_worldgen_threading_issues)
		Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.71+1.21.1 (c2me_fixes_worldgen_vanilla_bugs)
		Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.71+1.21.1 (c2me_notickvd)
		Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.71+1.21.1 (c2me_opts_chunkio)
		Concurrent Chunk Management Engine (Optimizations/Density Function Compiler) 0.3.0+alpha.0.71+1.21.1 (c2me_opts_dfc)
		Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.71+1.21.1 (c2me_opts_worldgen_general)
		Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.71+1.21.1 (c2me_opts_math)
		Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.71+1.21.1 (c2me_opts_allocs)
		Concurrent Chunk Management Engine (Optimizations/Natives Math) 0.3.0+alpha.0.71+1.21.1 (c2me_opts_natives_math)
		Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.71+1.21.1 (c2me_opts_scheduling)
		Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.71+1.21.1 (c2me_opts_worldgen_vanilla)
		Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.71+1.21.1 (c2me_rewrites_chunkio)
		Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.71+1.21.1 (c2me_rewrites_chunk_serializer)
		Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.71+1.21.1 (c2me_rewrites_chunk_system)
		Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.71+1.21.1 (c2me_server_utils)
		Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.71+1.21.1 (c2me_threading_lighting)
		conditional mixin 0.6.4 (conditional_mixin)
		Corpse 1.21.1-1.1.10 (corpse)
		Create 6.0.6 (create)
		Create Encased 1.7.1-fix2 (createcasing)
		Create New Beginnings 0.1.0 (createnewbeg)
		Create Slice & Dice 4.0.1 (sliceanddice)
		Create: Dragons Plus 1.6.1 (create_dragons_plus)
		Create: Enchantment Industry 2.1.7 (create_enchantment_industry)
		Create: Integrated Farming 1.0.6 (create_integrated_farming)
		Create: Trading Floor 3.0.10 (trading_floor)
		Create: Winery 1.7.0 (create_winery)
		Distant Horizons 2.3.4-b-dev (distanthorizons)
		Farmer's Delight 1.2.8 (farmersdelight)
		Ferrite Core 7.0.2 (ferritecore)
		Flerovium 1.0.4 (flerovium)
		Flywheel 1.0.4 (flywheel)
		Forgified Fabric API Base 0.4.42+d1308ded19 (fabric_api_base)
		Forgified Fabric BlockView API (v2) 1.0.10+9afaaf8c19 (fabric_block_view_api_v2)
		Forgified Fabric Renderer API (v1) 3.4.0+acb05a3919 (fabric_renderer_api_v1)
		Forgified Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19 (fabric_rendering_data_attachment_v1)
		Fzzy Config 0.6.9+1.21+neoforge (fzzy_config)
		Iris 1.8.12-snapshot+mc1.21.1-local (iris)
		Jade 15.10.2+neoforge (jade)
		Jade Addons 6.1.0+neoforge (jadeaddons)
		Just Enough Items 19.22.0.315 (jei)
		Kotlin For Forge 5.8.0 (kotlinforforge)
		Lithium 0.15.0+mc1.21.1 (lithium)
		Minecraft 1.21.1 (minecraft)
		ModernFix 5.24.3+mc1.21.1 (modernfix)
		NeoForge 21.1.176 (neoforge)
		Ponder 1.0.56 (ponder)
		ShulkerBoxTooltip 5.1.6+1.21.1 (shulkerboxtooltip)
		Sodium 0.6.13+mc1.21.1 (sodium)
		VisibleToggleSprint 1.7.0 (visible_toggle_sprint)
		What Am I Listening To? 21.0.2.0 (wailt)
```
</details>

**Comment by fabien-gigante** [comment]
Trying to pindown this problem, which is annoying me.  I've narrowed it down to :
### Working
<details>
<summary>Client Info</summary>

```
Create:
	Mod Version: 6.0.6
	Mod Git Commit: unknown
	Ponder Version: 1.0.56
	NeoForge Version: 21.1.176
	Minecraft Version: 1.21.1

Graphics:
	Flywheel Version: 1.0.4
	Flywheel Backend: flywheel:indirect
	OpenGL Renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGL Version: 4.6.0 NVIDIA 560.94
	Graphics Mode: fancy
	PojavLauncher Detected: false

System Information:
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 22.0.2, Oracle Corporation
	JVM Flags: 35 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -Xms12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:NmethodSweepActivity=1 -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:AllocatePrefetchStyle=3 -XX:+DisableExplicitGC -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:-DontCompileHugeMethods
	Memory: 11279168048 bytes (10756 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	Total Memory: 1607406288 bytes (1532 MiB) / 12884901888 bytes (12288 MiB)
	CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz @ 3.54 GHz; 4 cores / 8 threads on 1 socket(s)
	Graphics cards: none

Other Mods:
	Farmer's Delight: 1.2.8
	Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Threading/Lighting): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	Jade: 15.10.2+neoforge
	Concurrent Chunk Management Engine (Client/Uncap View Distance): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Rewrites/Chunk Serializer): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Server Utils): 0.3.0+alpha.0.71+1.21.1
	Just Enough Items: 19.22.0.315
	Concurrent Chunk Management Engine (Optimizations/Natives Math): 0.3.0+alpha.0.71+1.21.1
	Kotlin For Forge: 5.8.0
	Concurrent Chunk Management Engine (Optimizations/Density Function Compiler): 0.3.0+alpha.0.71+1.21.1
	Create: Dragons Plus: 1.6.1
	Concurrent Chunk Management Engine (Fixes/General/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	What Am I Listening To?: 21.0.2.0
	Concurrent Chunk Management Engine (No Tick View Distance): 0.3.0+alpha.0.71+1.21.1
	Create: Integrated Farming: 1.0.6
	Concurrent Chunk Management Engine (Optimizations/General WorldGen): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Chunk IO): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Math): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine: 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Rewrites/Chunk System): 0.3.0+alpha.0.71+1.21.1
	conditional mixin: 0.6.4
	VisibleToggleSprint: 1.7.0
	Crate Delight: 24.11.22-1.21-neoforge
	Concurrent Chunk Management Engine (Base): 0.3.0+alpha.0.71+1.21.1
	Jade Addons: 6.1.0+neoforge
	Concurrent Chunk Management Engine (Rewrites/Chunk IO): 0.3.0+alpha.0.71+1.21.1
	Fzzy Config: 0.6.9+1.21+neoforge
	Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Scheduling): 0.3.0+alpha.0.71+1.21.1
	Create: Enchantment Industry: 2.1.7
	Concurrent Chunk Management Engine (Optimizations/Memory Allocations): 0.3.0+alpha.0.71+1.21.1
	Create Slice & Dice: 4.0.1
```

</details>


<details>
<summary>Server Info</summary>

```
Create:
	Mod Version: 6.0.6
	Mod Git Commit: unknown
	Ponder Version: 1.0.56
	NeoForge Version: 21.1.176
	Minecraft Version: 1.21.1

System Information:
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 22.0.2, Oracle Corporation
	JVM Flags: 35 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -Xms12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:NmethodSweepActivity=1 -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:AllocatePrefetchStyle=3 -XX:+DisableExplicitGC -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:-DontCompileHugeMethods
	Memory: 11279168048 bytes (10756 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	Total Memory: 1607406288 bytes (1532 MiB) / 12884901888 bytes (12288 MiB)
	CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz @ 3.54 GHz; 4 cores / 8 threads on 1 socket(s)
	Graphics cards: none

Other Mods:
	Farmer's Delight: 1.2.8
	Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Threading/Lighting): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	Jade: 15.10.2+neoforge
	Concurrent Chunk Management Engine (Client/Uncap View Distance): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Rewrites/Chunk Serializer): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Server Utils): 0.3.0+alpha.0.71+1.21.1
	Just Enough Items: 19.22.0.315
	Concurrent Chunk Management Engine (Optimizations/Natives Math): 0.3.0+alpha.0.71+1.21.1
	Kotlin For Forge: 5.8.0
	Concurrent Chunk Management Engine (Optimizations/Density Function Compiler): 0.3.0+alpha.0.71+1.21.1
	Create: Dragons Plus: 1.6.1
	Concurrent Chunk Management Engine (Fixes/General/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	What Am I Listening To?: 21.0.2.0
	Concurrent Chunk Management Engine (No Tick View Distance): 0.3.0+alpha.0.71+1.21.1
	Create: Integrated Farming: 1.0.6
	Concurrent Chunk Management Engine (Optimizations/General WorldGen): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Chunk IO): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Math): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine: 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Rewrites/Chunk System): 0.3.0+alpha.0.71+1.21.1
	conditional mixin: 0.6.4
	VisibleToggleSprint: 1.7.0
	Crate Delight: 24.11.22-1.21-neoforge
	Concurrent Chunk Management Engine (Base): 0.3.0+alpha.0.71+1.21.1
	Jade Addons: 6.1.0+neoforge
	Concurrent Chunk Management Engine (Rewrites/Chunk IO): 0.3.0+alpha.0.71+1.21.1
	Fzzy Config: 0.6.9+1.21+neoforge
	Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Scheduling): 0.3.0+alpha.0.71+1.21.1
	Create: Enchantment Industry: 2.1.7
	Concurrent Chunk Management Engine (Optimizations/Memory Allocations): 0.3.0+alpha.0.71+1.21.1
	Create Slice & Dice: 4.0.1
```

</details>

### Not working
<details>
<summary>Client Info</summary>

```
Create:
	Mod Version: 6.0.6
	Mod Git Commit: unknown
	Ponder Version: 1.0.56
	NeoForge Version: 21.1.176
	Minecraft Version: 1.21.1

Graphics:
	Flywheel Version: 1.0.4
	Flywheel Backend: flywheel:indirect
	OpenGL Renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGL Version: 4.6.0 NVIDIA 560.94
	Graphics Mode: fancy
	PojavLauncher Detected: false

System Information:
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 22.0.2, Oracle Corporation
	JVM Flags: 35 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -Xms12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:NmethodSweepActivity=1 -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:AllocatePrefetchStyle=3 -XX:+DisableExplicitGC -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:-DontCompileHugeMethods
	Memory: 11358587048 bytes (10832 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	Total Memory: 1541328432 bytes (1469 MiB) / 12884901888 bytes (12288 MiB)
	CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz @ 3.54 GHz; 4 cores / 8 threads on 1 socket(s)
	Graphics cards: none

Other Mods:
	Farmer's Delight: 1.2.8
	Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Threading/Lighting): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	Jade: 15.10.2+neoforge
	Concurrent Chunk Management Engine (Client/Uncap View Distance): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Rewrites/Chunk Serializer): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Server Utils): 0.3.0+alpha.0.71+1.21.1
	Just Enough Items: 19.22.0.315
	Concurrent Chunk Management Engine (Optimizations/Natives Math): 0.3.0+alpha.0.71+1.21.1
	Kotlin For Forge: 5.8.0
	Concurrent Chunk Management Engine (Optimizations/Density Function Compiler): 0.3.0+alpha.0.71+1.21.1
	Create: Dragons Plus: 1.6.1
	Concurrent Chunk Management Engine (Fixes/General/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	What Am I Listening To?: 21.0.2.0
	Concurrent Chunk Management Engine (No Tick View Distance): 0.3.0+alpha.0.71+1.21.1
	Create: Integrated Farming: 1.0.6
	Concurrent Chunk Management Engine (Optimizations/General WorldGen): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Chunk IO): 0.3.0+alpha.0.71+1.21.1
	Create Encased: 1.7.1-fix2
	Concurrent Chunk Management Engine (Optimizations/Math): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine: 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Rewrites/Chunk System): 0.3.0+alpha.0.71+1.21.1
	conditional mixin: 0.6.4
	VisibleToggleSprint: 1.7.0
	Crate Delight: 24.11.22-1.21-neoforge
	Concurrent Chunk Management Engine (Base): 0.3.0+alpha.0.71+1.21.1
	Jade Addons: 6.1.0+neoforge
	Concurrent Chunk Management Engine (Rewrites/Chunk IO): 0.3.0+alpha.0.71+1.21.1
	Fzzy Config: 0.6.9+1.21+neoforge
	Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Scheduling): 0.3.0+alpha.0.71+1.21.1
	Create: Enchantment Industry: 2.1.7
	Concurrent Chunk Management Engine (Optimizations/Memory Allocations): 0.3.0+alpha.0.71+1.21.1
	Create Slice & Dice: 4.0.1
```

</details>


<details>
<summary>Server Info</summary>

```
Create:
	Mod Version: 6.0.6
	Mod Git Commit: unknown
	Ponder Version: 1.0.56
	NeoForge Version: 21.1.176
	Minecraft Version: 1.21.1

System Information:
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 22.0.2, Oracle Corporation
	JVM Flags: 35 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -Xms12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:NmethodSweepActivity=1 -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:AllocatePrefetchStyle=3 -XX:+DisableExplicitGC -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:-DontCompileHugeMethods
	Memory: 11358587048 bytes (10832 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	Total Memory: 1541328432 bytes (1469 MiB) / 12884901888 bytes (12288 MiB)
	CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz @ 3.54 GHz; 4 cores / 8 threads on 1 socket(s)
	Graphics cards: none

Other Mods:
	Farmer's Delight: 1.2.8
	Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Threading/Lighting): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	Jade: 15.10.2+neoforge
	Concurrent Chunk Management Engine (Client/Uncap View Distance): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Rewrites/Chunk Serializer): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Server Utils): 0.3.0+alpha.0.71+1.21.1
	Just Enough Items: 19.22.0.315
	Concurrent Chunk Management Engine (Optimizations/Natives Math): 0.3.0+alpha.0.71+1.21.1
	Kotlin For Forge: 5.8.0
	Concurrent Chunk Management Engine (Optimizations/Density Function Compiler): 0.3.0+alpha.0.71+1.21.1
	Create: Dragons Plus: 1.6.1
	Concurrent Chunk Management Engine (Fixes/General/Threading Issues): 0.3.0+alpha.0.71+1.21.1
	What Am I Listening To?: 21.0.2.0
	Concurrent Chunk Management Engine (No Tick View Distance): 0.3.0+alpha.0.71+1.21.1
	Create: Integrated Farming: 1.0.6
	Concurrent Chunk Management Engine (Optimizations/General WorldGen): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Chunk IO): 0.3.0+alpha.0.71+1.21.1
	Create Encased: 1.7.1-fix2
	Concurrent Chunk Management Engine (Optimizations/Math): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine: 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Rewrites/Chunk System): 0.3.0+alpha.0.71+1.21.1
	conditional mixin: 0.6.4
	VisibleToggleSprint: 1.7.0
	Crate Delight: 24.11.22-1.21-neoforge
	Concurrent Chunk Management Engine (Base): 0.3.0+alpha.0.71+1.21.1
	Jade Addons: 6.1.0+neoforge
	Concurrent Chunk Management Engine (Rewrites/Chunk IO): 0.3.0+alpha.0.71+1.21.1
	Fzzy Config: 0.6.9+1.21+neoforge
	Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs): 0.3.0+alpha.0.71+1.21.1
	Concurrent Chunk Management Engine (Optimizations/Scheduling): 0.3.0+alpha.0.71+1.21.1
	Create: Enchantment Industry: 2.1.7
	Concurrent Chunk Management Engine (Optimizations/Memory Allocations): 0.3.0+alpha.0.71+1.21.1
	Create Slice & Dice: 4.0.1
```

</details>

I don't think one mod in particular is responsible. It seems to be a combinaison of mods that causes the issue, or maybe the order in which the mods are loaded, not sure.

And by the way, `/flywheel backend flywheel:off` doesn't change anything to the problem either.

**Comment by fabien-gigante** [comment]
OK, I think I have a correction for this issue !

Defering registration of the visual and renderer to the actual regitration time, as follows, fixes the problem.
As opposed to doing so at class loading (with static initializers) which is apparently non predictable.

```kt
object Content {

    lateinit var SLICER_BLOCK_ENTITY: BlockEntityEntry<SlicerBlockEntity>

    fun register(container: ModContainer, modBus: IEventBus) {

        SLICER_BLOCK_ENTITY = REGISTRATE.blockEntity("slicer", BlockEntityFactory(::SlicerBlockEntity))
            .visual { SimpleBlockEntityVisualizer.Factory(::SlicerVisual) }
            .renderer { NonNullFunction { SlicerRenderer(it) } }.validBlock(SLICER_BLOCK).register()

```

PS : It's probably a good practice to do the same for all other `RegistryEntry` as well...

**Comment by PssbleTrngle** [comment]
Very nice, thank you all for your time and effort investigating this. Slice and dice will receive a new version within the next few weeks which should also address this then, it has just been the priority right now

**Comment by fabien-gigante** [comment]
You're welcome.
I have noticed another visual bug. When in `flywheel backend instancing` mode, the slicer head wasn't rotating.
Adding the missing line of code below fixes the issue :
```kt
class SlicerVisual(context: VisualizationContext, private val mixer: SlicerBlockEntity, partialTick: Float) :
    private val mixerHead = instancerProvider()
        .instancer(AllInstanceTypes.ROTATING, Models.partial(SlicerPartials.SLICER_HEAD))
        .createInstance()
        .setRotationAxis(Direction.Axis.Y)               //   <--  MISSING
        .also {
            SliceAndDice.LOGGER.info("SlicerVisual: mixerHead instance created with partial: ${SlicerPartials.SLICER_HEAD.modelLocation()}")
        }
```

**Comment by stirredkoala** [comment]
If this helps. i'm only encountering this bug when I have more than exactly 37 mods enabled.

**Comment by SuCrispy** [comment]
I also encountered a similar issue. I am using version 1.21.1 of Neoforge, and after troubleshooting, I found that the problem occurs when JEI is installed. The issue is resolved as long as JEI is removed. I'm not sure if it's the same situation as mentioned by the previous person, but I hope you can look into it

<img width="1448" height="947" alt="Image" src="https://github.com/user-attachments/assets/72272640-25f7-4ae1-b18c-795cee770e9f" />

**Comment by Anarchy-Angel** [comment]
Encountered same issue on 1.12.1 NeoForge version. 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/47624397-d3ed-45cf-9865-ca2c7cd400ba" />

**Comment by nerdman0** [comment]
I can confirm that this issue still occurs in 1.21.1 neoforge, and removing jei fixes it

**Comment by PssbleTrngle** [comment]
should finally be fixed in 4.2.1

**Comment by nerdman0** [comment]
Lets go! (sadly I gotta wait for my other addons to update to 6.0.7)

**Comment by PssbleTrngle** [comment]
ah sorry, I could have also fixed the bug in reverse and release a hotfix that still works with 6.0.6 first :/
