### ISSUE TITLE
[Crash] Crash on start-up with latest Slice & Dice version Fabric 0.14.21

### ISSUE THREAD

**Issue by pokesmells** [PssbleTrngle/SliceAndDice#80]
### What happened?

It crashes immediately on start-up.

https://mclo.gs/ZE65V8M - crash log

https://mclo.gs/E9WOJOR#L17 - latest log

### Loader

fabric

### Mod Version

sliceanddice-fabric-2.1.4-dev

### Minecraft Version

1.19

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-06-03 20:58:16
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'sliceanddice'!
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:459)
	at net.minecraft.client.main.Main.main(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/item/CreativeModeTab
	at com.possible_triangle.sliceanddice.Content.<clinit>(Content.kt:54)
	at com.possible_triangle.sliceanddice.SliceAndDice.onInitialize(SliceAndDice.java:17)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.item.CreativeModeTab
	at java.base@17.0.3/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base@17.0.3/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base@17.0.3/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:459)
Mixins in Stacktrace: None found

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23050.3 (91cf713774e4083376800dd3a1236363c5e087f6):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jna7250956394461143195.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.23466.1001 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		com.jozufozu.flywheel.mixin.ClientMainMixin (flywheel.mixins.json)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 836761600 bytes (797 MiB) / 2545942528 bytes (2428 MiB) up to 6408896512 bytes (6112 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3550
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 65473.16
	Virtual memory used (MB): 23036.90
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6112m -Xms256m
	Fabric Mods: 
		ad_astra: Ad Astra 1.12.6
		additionalstructures: Additional Structures 4.1.1
		adorn: Adorn 3.8.3+1.19.2
		advancementplaques: Advancement Plaques 1.4.6
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.18
		ae2: Applied Energistics 2 12.9.5
			noindium: No Indium? 1.1.0+1.19
		ae2wtlib: AE2WTLib 12.8.5
		airhop: Air Hop 4.2.1
		alloy_forgery: Alloy Forgery 2.0.20+1.19
		alternate-current: Alternate Current 1.5.0
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19.2
		appbot: Applied Botanics 1.4.3
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.85
		artifacts: Artifacts 7.1.1+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		auudio: Auudio 1.0.3
		awesomedungeon: Awesome dungeon 3.2.0
		awesomedungeonocean: Awesome dungeon edition ocean 3.2.0
		azurelib: AzureLib 1.0.19
			com_eliotlash_mclib_mclib: mclib 20
		balm-fabric: Balm 4.5.7
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.6
		beaconoverhaul: Beacon Overhaul 1.7.3+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		bendy-lib: Bendy api 2.1.1
		besmirchment: Besmirchment 1.19.2-10
			playerabilitylib: Pal 1.6.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		betteradvancements: Better Advancements 0.2.2.142
		betteranimalsplus: Better Animals Plus 1.19.2-11.0.10
		betteranimationscollection: Better Animations Collection 4.0.5
		bettercombat: Better Combat 1.7.1+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.5
		betterfortresses: YUNG's Better Nether Fortresses 1.19.2-Fabric-1.0.5
		betterfpsdist: Better FPS distance Mod 1.19-2.4
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		bettermounthud: Better Mount HUD 1.2.0
		betternether: Better Nether 7.1.3
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstats: Better Statistics Screen 2.8.1+1.19.2
			tcdcommons: TCD Commons API 2.8+1.19.2
		betterthirdperson: Better Third Person 1.9.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bewitchment: Bewitchment 1.19-7
			impersonate: Impersonate 2.8.0
		biomemakeover: Biome Makeover 1.19.2-1.6.4
		block_limit_fix: Block Limit Fix 1.0.3-fabric
		blur: Blur (Fabric) 2.6.0
		boatbreakfix: Boat Break Fix 1.0.11
		boatiview: Boat Item View Fabric 0.0.4
		bobby: Bobby 4.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 16.3.20
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.6-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		botania: Botania 1.19.2-440-FABRIC
			fiber: fiber 0.23.0-2
		botanypots: BotanyPots 9.0.33
		botanytrees: BotanyTrees 5.0.8
		botarium: Botarium 1.8.2
		bountiful: Bountiful 3.0.0
		bowinfinityfix: Bow Infinity Fix 2.5.0
		brewinandchewin: Brewin And Chewin fabric-1.0.6+1.19.2
		bwncr: Bad Wither No Cookie Reloaded 3.14.1
		bwplus: Bewitchment Plus 1.19-11
		byg: Oh The Biomes You'll Go 2.0.1.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		bygonenether: Bygone Nether 1.2.2
		cacao: Croptopia's Chocolaterie 1.2
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		carryon: Carry On 2.0.5.11
		catwalksinc: Catwalks Inc. 1.3.1
		cccbridge: CC:C Bridge 1.4.1
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charm_fixer: Charm Fixer 1.0.0
		chat_heads: Chat Heads 0.10.14
		chatpatches: Chat Patches 192.2.1
		chefsdelight: Chef's Delight 1.0.3-fabric-1.19.2
			structurized-reborn: Structurized Reborn 1.19-01
		chiselsandbits: chisels-and-bits 1.3.135
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			saeculariacaudices: Saecularia Caudices 1.0.16
			scena: Scena 1.0.95
		chunksending: Chunksending Mod 1.19-2.5
		chunksfadein: Chunks Fade In 3.0.11-1.19
		clarks_classes: Expanded Classes 1.19-4.0.2-FABRIC
		cleancut: CleanCut 1.19.2-5.1-fabric
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		clumps: Clumps 9.0.0+14
		collective: Collective 6.53
		combatroll: Combat Roll 1.1.5+1.19
		computercraft: CC: Restitched 1.101.2
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		configured: Configured 2.0.0
		conjuring: Conjuring 1.0.26+1.19
		connectivity: Connectivity Mod 1.19.2-4.2
		controlling: Controlling For Fabric 10.0+7
		cookingforblockheads: Cooking for Blockheads 13.3.2
		coralreef: Coral Reef 1.19-1.0.2
		corgilib: CorgiLib 1.0.0.34
		crawl: Crawl 0.11.1
			mm: Manningham Mills 2.3
		create: Create 0.5.0.i-1017+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.8.a-4
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.954+1.19.2
				porting_lib_accessors: Porting Lib Accessors 2.1.954+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.954+1.19.2
				porting_lib_base: Porting Lib Base 2.1.954+1.19.2
				porting_lib_common: Porting Lib Common 2.1.954+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.954+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.954+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.954+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.954+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.954+1.19.2
				porting_lib_loot: Porting Lib Loot 2.1.954+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.954+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.954+1.19.2
				porting_lib_models: Porting Lib Models 2.1.954+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.954+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.954+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.954+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			registrate-fabric: Registrate for Fabric 1.1.57-MC1.19.2
		createaddition: Create Crafts & Additions 20230508b
		creativecore: CreativeCore (Fabric) 2.9.3
		creeperoverhaul: Creeper Overhaul 2.0.9
		croptopia: Croptopia 2.2.2
		ctov: ChoiceTheorem's Overhauled Villages 3.2.2
		culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
		darkness: True Darkness 2.0.101
		darkwaters: Dark Waters 0.0.17
		dataattributes: Data Attributes 1.4.5+1.19.2
		debugify: Debugify 2.8.0
		dehydration: Dehydration 1.3.4
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		deuf_refabricated: DEUF Refabricated 1.0.0
		doom: Doom Fabric 5.0.4
		dragonfight: Dragonfight Mod 1.19.2-2.8
		drippyloadingscreen: Drippy Loading Screen 2.2.1
		dummmmmmy: MmmMmmMmmMmm 1.19.2-1.7.1
		dungeon_difficulty: Dungeon Difficulty 2.0.3+1.19
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		dungeons_arise: When Dungeons Arise 2.1.55
		dungeonz: DungeonZ 1.0.1
		easyanvils: Easy Anvils 4.0.11
		easymagic: Easy Magic 4.3.3
		eatinganimationid: Eating Animation 1.9.1
		ecologics: Ecologics 2.1.11
		eldritch_mobs: EldritchMobs 1.12.11
			polymer: Polymer (Core) 0.2.18+1.19.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			polymer-blocks-ext: Polymer Blocks 0.1.0-alpha.9+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		elytraslot: Elytra Slot 6.1.1+1.19.2
		emojiful: Emojiful 4.0.4
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
		emotecraft: Emotecraft 2.2.5
		enchantinginfuser: Enchanting Infuser 4.2.2
		endrem: End Remastered 5.2.0
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.9
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		enviromats: Environmental Materials 1.19-2.1.1.0
		environmentz: EnvironmentZ 2.0.5
			satin: Satin 1.9.0
		equipmentcompare: Equipment Compare 1.3.1
		essential_commands: Essential Commands 0.33.0-mc1.19.2
			ec-core: Essential Commands Core 1.3.0-mc1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			org_yaml_snakeyaml: snakeyaml 1.33
		expandeddelight: Expanded Delight 0.2.5.2
		explorify-fabric: Explorify 1.19-1.3.0
		extraalchemy: Extra Alchemy 1.9.0
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-furnaces: Fabric Furnaces 2.2.0-1.19.2
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricenchantments: Fabric Enchantments 0.9.0
		fabricloader: Fabric Loader 0.14.21
		fabrishot: Fabrishot 1.9.2
		fallingtree: FallingTree 3.10.0
		fancymenu: FancyMenu 2.14.7
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersknives: Farmer's Knives 2.4
		fastfurnace: FastFurnace 1.19.2-5
		ferritecore: FerriteCore 5.0.3
		findme: FindMe 3.1.0
		fishofthieves: Fish of Thieves 2.2.3
		fmextension_audio: FancyMenu Audio Extension 1.1.1
		foodplusid: Food+ 1.4.1
		forgeconfigapiport: Forge Config API Port 4.2.11
		fpsreducer: FPS Reducer 1.19.2-2.1
		friendsandfoes: Friends&Foes 1.8.2
		ftblibrary: FTB Library 1902.3.19-build.214
		ftbquests: FTB Quests 1902.4.16-build.235
		ftbteams: FTB Teams 1902.2.13-build.100
		fwaystones: Fabric Waystones 3.0.7+mc1.19.2
		gazebo: Gazebos 1.0.0+1.19.2
		geckolib3: Geckolib 3.1.40
		go-fish: Go Fish 1.6.0-1.19.1
		goblintraders: Goblin Traders 1.8.1
		graveyard: The Graveyard 2.3.3
		graveyard_biomes: The Graveyard Biomes 1.6
		guardvillagers: Guard Villagers Fabric 1.19.2-1.1.2
		handcrafted: Handcrafted 2.0.6
		harvestwithease: Harvest with ease 6.0.1.2-final
		healingcampfire: Healing Campfire 5.1
		highlight: Highlight 1.0.0
		highlighter: Highlighter 1.1.4
		icarus: Icarus 1.14
		iceberg: Iceberg 1.0.46
		idwtialsimmoedm: idwtialsimmoedm 0.2.0+1.19
		immediatelyfast: ImmediatelyFast 1.1.12
			net_lenni0451_reflect: Reflect 1.1.0
		immersive_armors: Immersive Armors 1.5.5+1.19.2
		immersive_paintings: Immersive Paintings 0.6.0+1.19.2
		imst: Immersive structures 2.0.7a
		imst_n: Immersive Structures:Nether edition 1.0.0
		incantationem: Incantationem 1.1.6+1.19
		indium: Indium 1.0.9+mc1.19.2
		indrev: Industrial Revolution 1.15.1-BETA
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		integrated_api: Integrated API 1.2.7+1.19.2
		integrated_stronghold: Integrated Stronghold 1.0.2+1.19.2
		interactic: Interactic 0.1.11+1.19
		inventoryhud: Inventory HUD + 3.4.7
		inventoryprofilesnext: Inventory Profiles Next 1.10.2
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		ironchests: Iron Chests: Restocked 3.1.1
		item_obliterator: Item Obliterator 1.2.0
		itemfilters: Item Filters 1902.2.9-build.51
		jade: Jade 8.7.3
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 4.0-1.19.2
		kiwi: Kiwi Lib 8.3.3
		kleeslabs: KleeSlabs 12.3.0
		konkrete: Konkrete 1.6.1
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		languagereload: Language Reload 1.5.6+1.19.2
		lazydfu: LazyDFU 0.1.3
		leavesbegone: Leaves Be Gone 4.0.1
		legendarytooltips: Legendary Tooltips 1.3.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		libipn: libIPN 3.0.1
		libraryferret: Library ferret 4.0.0
		libz: LibZ 1.0.0
		limitedchunks: Limited Chunkloading Mod 1.19.2-2.6
		lithium: Lithium 0.11.1
		logbegone: Log Begone 1.0.6
		lookaround: Lookaround! 0.11.4
		lootintegrations: Loot integration Mod 1.19.3-3.1
		lootr: Lootr 0.4.26.65
		luggage: Luggage 1.19-1.5.2
			forge_tags: Porting Lib Tags 3.0
		magnumtorch: Magnum Torch 4.2.2
		mcda: MC Dungeons Armors 2.4.4
		mcdar: MC Dungeons Artifacts 1.5.3-1.19
		mcdw: MC Dungeons Weapons 5.0.11-1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			enchant_giver: Enchant Giver 1.3.0
		meadow: Meadow 1.1.1
		measurements: Measurements 1.3.1
		megacells: MEGA Cells 2.0.0-beta.11-1.19.2
		memoryleakfix: Memory Leak Fix 1.0.0
		merequester: ME Requester 1.19.2-1.1.2
		midnightlib: MidnightLib 1.0.0
		minecells: Mine Cells 1.4.3
		minecraft: Minecraft 1.19.2
		mixintrace: MixinTrace 1.1.1+1.17
		mo_glass: Mo Glass 1.6.1-MC1.19.2
		modelfix: Model Gap Fix 1.8
		modern_industrialization: Modern Industrialization 1.6.8
			magna: Magna 1.8.0-1.19
		moderndynamics: Modern Dynamics 0.6.1-beta
		modernfix: ModernFix 3.7.1
		modmenu: Mod Menu 4.1.2
		modpack-update-checker: Modpack Update Checker 0.5.1
		moonlight: Moonlight 1.19.2-2.2.36
		moreculling: More Culling 1.19.1-0.17.0
			conditional-mixin: conditional mixin 0.3.0
		mostructures: Mo' Structures 1.4.3+1.19.2
		mutantmonsters: Mutant Monsters 4.0.5
		mythicmetals: Mythic Metals 0.17.3+1.19.2
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19
		mythicmounts: Mythic Mounts 1.19.2-7.2
		nameplate: Nameplate 1.1.3
		naturalist: Naturalist 3.0.3a
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		netherportalfix: NetherPortalFix 10.0.1
		nethersdelight: Nether's Delight 1.0.1
			disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		nightconfigfixes: Night Config Fixes 4.0.7
		nnvf: No Night Vision Flickering 0.1.3
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		numismatic-overhaul: Numismatic Overhaul 0.2.8+1.19
			stacc: Stacc 1.3.3
		numismaticclaim: Numismatic Claim 1.0.8
		oceansdelight: Ocean's Delight 1.0.0
		opaccreatesupport: OPAC Create Mod Support 1.1.1
		openpartiesandclaims: Open Parties and Claims 0.17.3
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				calio: Calio 1.7.0
		origins-classes: Origins: Classes 1.4.0
		origins-plus-plus: Origins++ 2.0.1
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		paladins: Paladins & Priests 0.9.6+1.19.2
		passablefoliage: Passable Foliage 1.19-fabric-5.0.2
		patchouli: Patchouli 1.19.2-77-FABRIC
		paxi: Paxi 1.19.2-Fabric-3.0.1
		pehkui: Pehkui 3.7.5+1.14.4-1.20
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		pfm: Paladin's Furniture 1.1.1
		philipsruins: Philip`s Ruins 1.19.2
		pickupnotifier: Pick Up Notifier 4.2.4
		ping-wheel: Ping Wheel 1.3.0
		player-animator: Player Animator 1.0.2
		playerex: PlayerEx 3.5.2
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.4
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.46.1+1.19.2
		powah: Powah! 4.0.10
		presencefootsteps: Presence Footsteps 1.6.4
			kirin: Kirin UI 1.11.1
		prism: Prism 1.0.3
		probablychests: Probably Chests 0.5.5-1.19.2
		professions: Professions 1.0.5
			octo-economy-api: Octo Economy API 1.1.0
		professionsi: Professions Integrations 1.0.4
		projectile_damage: Projectile Damage Attribute 3.2.1+1.19
		puzzle: Puzzle 1.4.2-1.19
			puzzle-base: Puzzle Base 1.4.2-1.19
			puzzle-gui: Puzzle GUI 1.4.2-1.19
			puzzle-models: Puzzle Models 1.4.2-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.2-1.19
		puzzleslib: Puzzles Lib 4.4.0
		quartzelv: Quartz Elevator 2.1.5+1.19
		reacharound: Reacharound 1.1.2
		realisticbees: Realistic Bees 3.3
		reborncore: Reborn Core 5.4.0
			team_reborn_energy: Energy 2.3.0
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		regions_unexplored: Regions Unexplored 0.4.1+1.19.2
		relicex: RelicEx 3.3.1+1.19.2
			armorrenderlib: Armor Render Lib 0.2.6
		repurposed_structures: Repurposed Structures 6.3.24+1.19.2
		resourcefulconfig: Resourcefulconfig 1.0.20
		resourcefullib: Resourceful Lib 1.1.24
		resourcepackoverrides: Resource Pack Overrides 4.0.4
		riverredux: River Redux 0.3.0
		rocks: This Rocks! 1.6.1
		rottencreatures: Rotten Creatures 1.0.1
		roughly_enough_loot_tables: Roughly Enough Loot Tables 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.615
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.4
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		rpgdifficulty: Rpg Difficulty 1.3.12
		runes: Runes 0.9.8+1.19
		scout: Scout 1.1.2
		shouldersurfing: Shoulder Surfing Reloaded 2.3.2
		showmeyourskin: Show Me Your Skin! 1.6.3+1.19.2
			cicada: CICADA 0.4.0
		simple-rpc: Simple RPC 3.2.2
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.2.13
		simplehats: SimpleHats 1.19.2-0.1.6
		simplyswords: Simply Swords 1.47.0-1.19.2
		skeletalremains: Skeletal Remains 1.3.2
			omega-config: OmegaConfig 1.3.0+1.19.2
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		skyvillages: Sky Villages 1.0.2.1
		sliceanddice: Create Slice & Dice 2.1.4
		smallships: Small Ships 2.0.0a2.2
		smartbrainlib: SmartBrainLib 1.9
		smarterfarmers: Smarter Farmers 1.19.2-1.7.2
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		soulsweapons: Marium's Soulslike Weaponry 0.9.9.3
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spell_engine: Spell Engine 0.9.24+1.19
		spell_power: Spell Power Attribute 0.9.12+1.19
		spellbladenext: Spellblades and Such 1.0.24.0
		spirit: Spirit 2.2.6
		stackdeobfuscator: StackDeobfuscator 1.3.2+fabric.4bca927
			net_fabricmc_mapping-io: mapping-io 0.3.0
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit: Starter Kit 5.2
		structory: Structory 1.0.1
		structory_towers: Structory: Towers 1.0.0
		structureessentials: Structure Essentials Mod 1.19.2-2.8
		stylisheffects: Stylish Effects 4.3.4
		supplementaries: Supplementaries 1.19.2-2.3.16
		t_and_t: Towns and Towers 1.10
		takesapillage: Takes a Pillage 1.0.4
		talkbubbles: Talk Bubbles 1.0.4
		techreborn: Tech Reborn 5.4.0
		terrablender: TerraBlender 2.0.1.136
		the_bumblezone: The Bumblezone - Fabric 6.7.22+1.19.2
			fake-player-api: Fake Player API 0.5.0
		things: Things 0.3.0+1.19
		tiered: Tiered 1.2.7
		tipsmod: Tips 8.0.27
		toolstats: ToolStats 12.0.2
		tooltipfix: ToolTip Fix 1.1.1-1.19
		totw_additions: Towers of the Wild: Additions 1.2.4
		tr-patchouli: Tech Reborn Patchouli 2.1.1
		tradingpost: Trading Post 4.2.0
		trashslot: TrashSlot 12.0.2
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.22
		travelerstitles: Traveler's Titles 1.19.2-Fabric-3.1.0
		trinkets: Trinkets 3.4.2
		tumbleweed: Tumbleweed 0.5.1
		twilightforest: The Twilight Forest 4.2.357
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
		valkyrielib: ValkyrieLib 1.19-4.0.1.1
		vanityslots: Vanity Slots 1.2.8
		varietyaquatic: Variety Aquatic 1.0.4.2
		veinmining: Vein Mining 1.1.1+1.19.2
			spectrelib: SpectreLib 0.12.3+1.19.2
		villagernames: Villager Names 4.5.1
		vinery: Vinery 1.2.11
			doapi: Lets Do Api 1.0.4
		visuality: Visuality 0.5.6
		visualworkbench: Visual Workbench 4.2.4
		vitalize: Vitalize 1.1.1
		voicechat: Simple Voice Chat 1.19.2-2.4.8
		voidtotem: Void Totem 2.1.0
		voidz: VoidZ 1.0.9
		waveycapes: WaveyCapes 1.3.2
		wetlands: Beneath the Wetlands 1.0.2
		whisperwoods: Whisperwoods 1.19-2.1.1
		windchimes: Windchimes 1.2.1
		wizardex: WizardEx 1.0.3
		wizards: Wizards 0.9.17+1.19
		wmitaf: WMITAF 3.1.1
		wondrouswilds: Wondrous Wilds 1.19.2-1.1.6
		xaerominimap: Xaero's Minimap 23.4.4
		xaeroworldmap: Xaero's World Map 1.30.3
		xlpackets: XLPackets 1.19.2-4
		xps: Xp Obelisk 0.4.9-r+1.19.2-Fabric
		xps_additions: XP Obelisk Additions 0.1.9-r+1.19.2-Fabric
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.9
		yosbr: YOSBR 0.1.1
		ysns: You Shall Not Spawn! 1.0.3
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
		zoomify: Zoomify 2.9.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.5
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.5
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.5
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.5
	Flywheel Backend: Uninitialized
	Launched Version: fabric-loader-0.14.21-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by PssbleTrngle** [comment]
I think this was caused by the wrong jar file being uploaded, it hopefully should be fixed in version 2.1.5

**Comment by SplendidAlakey** [comment]
Version 2.1.5 still crashes on startup, but with different logs: https://gist.github.com/SplendidAlakey/5880df77944cd6c64970dd50ca03b2c2

**Comment by EvanHsieh0415** [comment]
me too
https://mclo.gs/iRwxceA

**Comment by PssbleTrngle** [comment]
The mixin refmap seems to still be missing, probably because I named it wrong. Will fix this tomorrow

**Comment by PssbleTrngle** [comment]
The mixin refmap should now be named correctly & the build not longer crash
